# railway.toml

[build]
builder = "nixpacks"

[build.nixpacks]
# This ensures the `psql` command is available
pkgs = ["postgresql"]

[deploy]
# This command now runs your "postdeploy" script first,
# and if it succeeds, it starts your main application.
startCommand = "npm run postdeploy && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10